name: Release Creation
on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Install Dependencies
      run: npm ci

    - name: Build Packs
      run: npm run pullYMLtoLDB


name: Create Module Files For GitHub Release

env:
  project_url: 'https://github.com/WBHarry/pf2e-bestiary-tracking'
  version_manifest_url: 'https://github.com/WBHarry/pf2e-bestiary-tracking/releases/download/${{github.event.release.tag_name}}/module.json'
  version_module_url: 'https://github.com/WBHarry/pf2e-bestiary-tracking/releases/download/${{github.event.release.tag_name}}/module.zip'
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

      - name: Install Dependencies
        run: npm ci

      - name: Build Packs
        run: npm run pullYMLtoLDB