name: Create Pack Files

env:
  project_url: 'https://github.com/WBHarry/pf2e-bestiary-tracking'
  version_manifest_url: 'https://github.com/WBHarry/pf2e-bestiary-tracking/releases/download/${{github.event.release.tag_name}}/module.json'
  version_module_url: 'https://github.com/WBHarry/pf2e-bestiary-tracking/releases/download/${{github.event.release.tag_name}}/module.zip'
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install Dependencies
        run: npm ci

      - name: Build Packs
        run: npm run pullYMLtoLDB